@serverUrl = http://localhost:9000
@traderId = 2583e36b-e792-4ba7-8827-cbeb5c6af24a

### CREATE TARADER
POST {{serverUrl}}/api/trader
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiYWRtaW4iLCJpZCI6IjcxYmU5MDdiLWEwZjQtNDcxNi04Mjc3LWNlNjcxZTYxMDI1YiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.olGTWi4WX-3oaapfUUZf8QVf3ilQ4vnJ1Ldw1nKR3wOxUAZaOiEFVFmhYtFdNz7TcsuCtm0IqzyBOl7uj_XDtw
Content-Type: application/json

{
    "id": "{{$guid}}",
    "login": "login{{$guid}}",
    "password": "password",   
    "name": "name@{{$guid}}",
    "email": "email@{{$guid}}",
    "phone": {{$randomInt 48500000001 48590000001}}
}